services:
  database:
    image: postgres:latest
    container_name: database
    hostname: database
    ports:
      - 5432
    volumes:
      - ./database/:/var/lib/postgresql/data/
    env_file: template.env
  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    hostname: server
    ports:
      - "8080:8080"
    env_file: template.env
    depends_on:
      - database
